# Generated by Django 3.2.4 on 2021-09-03 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milma_id', models.IntegerField()),
                ('Qty', models.FloatField()),
                ('Fat', models.FloatField()),
                ('Clr', models.FloatField()),
                ('Snf', models.FloatField()),
                ('Rate', models.FloatField()),
                ('Amount', models.FloatField()),
                ('AM_Pm', models.CharField(max_length=1)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('telegram_id', models.CharField(max_length=255)),
                ('milma_id', models.IntegerField()),
                ('phone', models.CharField(max_length=255)),
                ('pword', models.CharField(max_length=5)),
            ],
        ),
    ]
